export const RouteName = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  TIMELINE: "TIMELINE",
  CREATE_POST: "CREATE_POST",
  PROFILE: "PROFILE",
  COMMENT: "COMMENT",
  SETTING: "SETTING",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  FOLLOWING: "FOLLOWING",
  FOLLOWERS: "FOLLOWERS",
};
